name: travel_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  avatar_stack: ^1.2.0
  curved_labeled_navigation_bar: ^2.0.2
  firebase_auth: ^4.16.0
  flutter:
    sdk: flutter
  flutter_calendar_week: ^3.0.2
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.0+3
  ultimate_bottom_navbar: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
